
/* File generated by gen_cfile.py. Should not be modified. */

#include "TestAllSlave.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 data[] =		/* Mapped at index 0x2000, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 sdo_data = 0x3;		/* Mapped at index 0x2001, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 TestAllSlave_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 TestAllSlave_bDeviceNodeId = 0x02;

/**************************************************************************/
/* Array of message processing information */

const UNS8 TestAllSlave_iam_a_slave = 1;

TIMER_HANDLE TestAllSlave_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 TestAllSlave_obj1000 = 0x0;	/* 0 */
                    subindex TestAllSlave_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&TestAllSlave_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 TestAllSlave_obj1001 = 0x0;	/* 0 */
                    subindex TestAllSlave_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestAllSlave_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 TestAllSlave_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 TestAllSlave_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex TestAllSlave_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&TestAllSlave_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestAllSlave_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 TestAllSlave_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 TestAllSlave_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 TestAllSlave_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 TestAllSlave_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 TestAllSlave_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 TestAllSlave_highestSubIndex_obj1016 = 0;
                    UNS32 TestAllSlave_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 TestAllSlave_obj1017 = 0x3E8;	/* 1000 */
                    subindex TestAllSlave_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&TestAllSlave_obj1017, NULL }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 TestAllSlave_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 TestAllSlave_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 TestAllSlave_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 TestAllSlave_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 TestAllSlave_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex TestAllSlave_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestAllSlave_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestAllSlave_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestAllSlave_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestAllSlave_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestAllSlave_obj1018_Serial_Number, NULL }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 TestAllSlave_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 TestAllSlave_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x602;	/* 1536 */
                    UNS32 TestAllSlave_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x582;	/* 1408 */
                    subindex TestAllSlave_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestAllSlave_highestSubIndex_obj1200, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestAllSlave_obj1200_COB_ID_Client_to_Server_Receive_SDO, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestAllSlave_obj1200_COB_ID_Server_to_Client_Transmit_SDO, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 TestAllSlave_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 TestAllSlave_obj1400_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 TestAllSlave_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestAllSlave_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestAllSlave_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestAllSlave_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestAllSlave_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestAllSlave_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestAllSlave_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestAllSlave_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestAllSlave_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestAllSlave_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestAllSlave_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestAllSlave_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestAllSlave_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 TestAllSlave_highestSubIndex_obj1600 = 4; /* number of subindex - 1*/
                    UNS32 TestAllSlave_obj1600[] = 
                    {
                      0x20000108,	/* 536871176 */
                      0x20000208,	/* 536871432 */
                      0x20000308,	/* 536871688 */
                      0x20000408	/* 536871944 */
                    };
                    subindex TestAllSlave_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestAllSlave_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestAllSlave_obj1600[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestAllSlave_obj1600[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestAllSlave_obj1600[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestAllSlave_obj1600[3], NULL }
                     };

/* index 0x2000 :   Mapped variable data */
                    UNS8 TestAllSlave_highestSubIndex_obj2000 = 4; /* number of subindex - 1*/
                    subindex TestAllSlave_Index2000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestAllSlave_highestSubIndex_obj2000, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&data[0], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&data[1], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&data[2], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&data[3], NULL }
                     };

/* index 0x2001 :   Mapped variable sdo_data */
                    subindex TestAllSlave_Index2001[] = 
                     {
                       { RW|TO_BE_SAVE, uint8, sizeof (UNS8), (void*)&sdo_data, NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable TestAllSlave_objdict[] = 
{
  { (subindex*)TestAllSlave_Index1000,sizeof(TestAllSlave_Index1000)/sizeof(TestAllSlave_Index1000[0]), 0x1000},
  { (subindex*)TestAllSlave_Index1001,sizeof(TestAllSlave_Index1001)/sizeof(TestAllSlave_Index1001[0]), 0x1001},
  { (subindex*)TestAllSlave_Index1017,sizeof(TestAllSlave_Index1017)/sizeof(TestAllSlave_Index1017[0]), 0x1017},
  { (subindex*)TestAllSlave_Index1018,sizeof(TestAllSlave_Index1018)/sizeof(TestAllSlave_Index1018[0]), 0x1018},
  { (subindex*)TestAllSlave_Index1200,sizeof(TestAllSlave_Index1200)/sizeof(TestAllSlave_Index1200[0]), 0x1200},
  { (subindex*)TestAllSlave_Index1400,sizeof(TestAllSlave_Index1400)/sizeof(TestAllSlave_Index1400[0]), 0x1400},
  { (subindex*)TestAllSlave_Index1600,sizeof(TestAllSlave_Index1600)/sizeof(TestAllSlave_Index1600[0]), 0x1600},
  { (subindex*)TestAllSlave_Index2000,sizeof(TestAllSlave_Index2000)/sizeof(TestAllSlave_Index2000[0]), 0x2000},
  { (subindex*)TestAllSlave_Index2001,sizeof(TestAllSlave_Index2001)/sizeof(TestAllSlave_Index2001[0]), 0x2001},
};

const indextable * TestAllSlave_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	(void)d;
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1017: i = 2;break;
		case 0x1018: i = 3;break;
		case 0x1200: i = 4;break;
		case 0x1400: i = 5;break;
		case 0x1600: i = 6;break;
		case 0x2000: i = 7;break;
		case 0x2001: i = 8;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &TestAllSlave_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status TestAllSlave_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index TestAllSlave_firstIndex = {
  4, /* SDO_SVR */
  0, /* SDO_CLT */
  5, /* PDO_RCV */
  6, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const quick_index TestAllSlave_lastIndex = {
  4, /* SDO_SVR */
  0, /* SDO_CLT */
  5, /* PDO_RCV */
  6, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const UNS16 TestAllSlave_ObjdictSize = sizeof(TestAllSlave_objdict)/sizeof(TestAllSlave_objdict[0]); 

CO_Data TestAllSlave_Data = CANOPEN_NODE_DATA_INITIALIZER(TestAllSlave);

