
/* File generated by gen_cfile.py. Should not be modified. */

#include "TestAll.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 data[] =		/* Mapped at index 0x2000, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 TestAll_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 TestAll_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 TestAll_iam_a_slave = 0;

TIMER_HANDLE TestAll_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 TestAll_obj1000 = 0x0;	/* 0 */
                    subindex TestAll_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&TestAll_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 TestAll_obj1001 = 0x0;	/* 0 */
                    subindex TestAll_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestAll_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 TestAll_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 TestAll_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex TestAll_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&TestAll_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestAll_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 TestAll_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 TestAll_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 TestAll_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 TestAll_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 TestAll_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 TestAll_highestSubIndex_obj1016 = 0;
                    UNS32 TestAll_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 TestAll_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 TestAll_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 TestAll_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 TestAll_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 TestAll_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 TestAll_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex TestAll_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestAll_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestAll_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestAll_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestAll_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestAll_obj1018_Serial_Number, NULL }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 TestAll_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 TestAll_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x602;	/* 1538 */
                    UNS32 TestAll_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x582;	/* 1410 */
                    UNS8 TestAll_obj1280_Node_ID_of_the_SDO_Server = 0x2;	/* 2 */
                    subindex TestAll_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestAll_highestSubIndex_obj1280, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestAll_obj1280_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestAll_obj1280_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestAll_obj1280_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 TestAll_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 TestAll_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 TestAll_obj1800_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestAll_obj1800_Inhibit_Time = 0xA;	/* 10 */
                    UNS8 TestAll_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestAll_obj1800_Event_Timer = 0x3E8;	/* 1000 */
                    UNS8 TestAll_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestAll_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestAll_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestAll_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestAll_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestAll_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestAll_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestAll_obj1800_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestAll_obj1800_SYNC_start_value, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 TestAll_highestSubIndex_obj1A00 = 4; /* number of subindex - 1*/
                    UNS32 TestAll_obj1A00[] = 
                    {
                      0x20000108,	/* 536871176 */
                      0x20000208,	/* 536871432 */
                      0x20000308,	/* 536871688 */
                      0x20000408	/* 536871944 */
                    };
                    subindex TestAll_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestAll_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestAll_obj1A00[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestAll_obj1A00[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestAll_obj1A00[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestAll_obj1A00[3], NULL }
                     };

/* index 0x2000 :   Mapped variable data */
                    UNS8 TestAll_highestSubIndex_obj2000 = 4; /* number of subindex - 1*/
                    subindex TestAll_Index2000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestAll_highestSubIndex_obj2000, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&data[0], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&data[1], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&data[2], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&data[3], NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable TestAll_objdict[] = 
{
  { (subindex*)TestAll_Index1000,sizeof(TestAll_Index1000)/sizeof(TestAll_Index1000[0]), 0x1000},
  { (subindex*)TestAll_Index1001,sizeof(TestAll_Index1001)/sizeof(TestAll_Index1001[0]), 0x1001},
  { (subindex*)TestAll_Index1018,sizeof(TestAll_Index1018)/sizeof(TestAll_Index1018[0]), 0x1018},
  { (subindex*)TestAll_Index1280,sizeof(TestAll_Index1280)/sizeof(TestAll_Index1280[0]), 0x1280},
  { (subindex*)TestAll_Index1800,sizeof(TestAll_Index1800)/sizeof(TestAll_Index1800[0]), 0x1800},
  { (subindex*)TestAll_Index1A00,sizeof(TestAll_Index1A00)/sizeof(TestAll_Index1A00[0]), 0x1A00},
  { (subindex*)TestAll_Index2000,sizeof(TestAll_Index2000)/sizeof(TestAll_Index2000[0]), 0x2000},
};

const indextable * TestAll_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	(void)d;
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1018: i = 2;break;
		case 0x1280: i = 3;break;
		case 0x1800: i = 4;break;
		case 0x1A00: i = 5;break;
		case 0x2000: i = 6;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &TestAll_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status TestAll_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index TestAll_firstIndex = {
  0, /* SDO_SVR */
  3, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  4, /* PDO_TRS */
  5 /* PDO_TRS_MAP */
};

const quick_index TestAll_lastIndex = {
  0, /* SDO_SVR */
  3, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  4, /* PDO_TRS */
  5 /* PDO_TRS_MAP */
};

const UNS16 TestAll_ObjdictSize = sizeof(TestAll_objdict)/sizeof(TestAll_objdict[0]); 

CO_Data TestAll_Data = CANOPEN_NODE_DATA_INITIALIZER(TestAll);

